# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.6'
- bash: |
    echo "##vso[task.setvariable variable=ROLE_REPO_NAME;isOutput=true]$(grep "role_name:" ${ROLE_META} | sed -e "s/.*role_name.* \(.*\)/\1/")"
    #export ROLE_REPO_NAME=$(grep "role_name:" ${ROLE_META} | sed -e "s/.*role_name.* \(.*\)/\1/")
    #export ROLE_NAME=$(grep "role_name:" ${ROLE_META} | sed -e "s/.*role_name.* \(.*\)/\1/" | sed "s/-/_/g")
    #export ROLE_NAMESPACE=$(grep "company:" ${ROLE_META} | sed -e "s/.*company.* \(.*\)/\1/" | sed "s/\./_/g")
    #export ROLE_NAME_FULL="$ROLE_NAMESPACE.$ROLE_NAME"
    echo ROLE_REPO_NAME=${ROLE_REPO_NAME}
    #echo ROLE_NAME=${ROLE_NAME}
    #echo ROLE_NAMESPACE=${ROLE_NAMESPACE}
    #echo ROLE_NAME_FULL=${ROLE_NAME_FULL}
  displayName: 'set variables'

# - bash: |
#     pip install testinfra molecule docker
#   displayName: 'install dependecies'

# - bash: |
#     cd ../
#     mv ansible-role-$ROLE_REPO_NAME $ROLE_NAME_FULL
#     cd $ROLE_NAME_FULL
#   displayName: 'rename role to match galaxy'

# - bash: |
#     molecule test
#   displayName: 'run molecule'

