---
- name: Converge
  hosts: instance
  become: true
  vars:
    local_role_name: "ansible-role-dispatcher"
    role_name: "{% if lookup('env','ROLE_NAME_FULL') %}{{ lookup('env','ROLE_NAME_FULL') }}{% else %}{{ local_role_name }}{% endif %}"
    test_container_name: "{{ local_role_name }}-test"
    test_aem_page: "AEM Sign In"

  pre_tasks:
    - name: get docker host ip
      become: true
      shell: |
        set -o pipefail
        /sbin/ip route | awk '/default/ { print $3 }'
      args:
        executable: /bin/bash
      register: dockerhost_ip
      changed_when: false

  roles:
    - {
      role: "aem_design.aem_license",
      aem_license_key: "{{ service_aem_license_key }}",
      aem_license_name: "{{ service_aem_license_name }}",
      aem_port: "5502",
      aem_host: "{{ dockerhost_ip.stdout }}",
      debug_hide: false
    }
    - {
      role: "aem_design.aem_verify",
      aem_port: "5502",
      aem_host: "{{ dockerhost_ip.stdout }}",
      debug_hide: false
    }
    - {
      role: "{{ role_name }}",
      renderer_port: "5502",
      renderer_host: "{{ dockerhost_ip.stdout }}",
      dispatcher_config: "author",
      docker_published_ports: [
        "9980:8080",
        "9981:8443"
      ],
      debug_hide: false
    }

  post_tasks:
    - name: wait until dispatcher return value from author {{ role_comment }}
      uri:
        url: "http://{{ dockerhost_ip.stdout }}:5502"
        return_content: true
        timeout: 300
        status_code: 403
      register: aem_page
      until: test_aem_page in aem_page.content
      delay: "{{ wait_delay | default(5) }}"
      retries: 360
